### ISSUE TITLE
Question coefficients and log change 

### ISSUE THREAD

**Issue by fifdick** [gosianow/DRIMSeq#3]
Hi,
I have been using your tool to test for DTU beween 2 groups (condition = case or control).
I was wondering whether the coefficient of the condition variable of the full model (extracted by DRIMSeq::coefficients(obj)) corresponds to the log (as in R log -> natural log) fold change of transcript expression between groups or to the log2 fold change. Im also using DEXSeq for the same purpose and want to compare fold changes. I think the DEXSeq coefficient corresponds to the log2 fold change. I also wondered and couldn't find it the documentation why some coefficients sør some transcripts are zero? Is this because I called the function on gene level? What exactly do the gene level coefficients mean? Id be glad for help.
Thanks, Fiona.

**Comment by gosianow** [comment]
Hi Fiona, 

in DRIMSeq we model proportions similarly like in logistic regression. But logistic regression could be applied only if you had two transcripts per gene. Since genes can have more than two transcripts, we use a multivariate version of the model which is an extension of the multinomial distribution. The coefficients from the DRIMSeq model correspond to log odds ratios (similarly like in logistic regression with binomial distribution). DEXSeq models counts using negative binomial distribution and yes, I think they use log2 transformation not log (natural). 

I hope that helps. Let me know.

**Comment by gosianow** [comment]
The difference between gene-level analysis and transcript-level analysis is that in gene-level we model all the transcripts at once using the Dirichlet-multinomial model (extension of multinomial) and we test if any of the transcripts changes the ratio of expression between conditions. With this approach we can only say if a gene has any transcript changing. With the transcript-level analysis we test each transcript separately using beta-binomial distribution (extension of binomial) so we test each transcript separately for change of its ratios between conditions. With this approach we can say which transcript changes. However, the underlying estimates of transcript proportions in the different conditions and the corresponding log odds ratios should be the same no matter if we estimate them with gene-level or transcript-level model.

**Comment by fifdick** [comment]
thanks for the detailed explanation. I actually see very nice agreement of log fold change between DEXSeq and DRIMSeq on transcript level when I transfer the coefficient (`log2(exp(coefficient))`); does it make sense to compare them like this?

**Comment by fifdick** [comment]
Hi again,

I have a follow up question and I was not sure if you'd want me to add
another issue for that.
I have described my use case above. And I looked at the p-value
distribution and I see a quite high peak around 1 as opposed to DEXSeq that
does not show that kind of distribution but rather uniform. I also
investigated if those 1-pvalue transcripts have a different mean expression
distribution than the rest of the transcripts, hypothesizing that those
might be very low expressed transcripts, but it didnt seem to be the case.
Im using a filter of minTxExpr=3 and minGeneExpr=10. Should I maybe
increase that? I also saw in the paper some similar looking p-value
distributions that looked more uniform or only had peaks around 0 when
using the moderated precision estimation, but this is already the default
of the precision estimation function anyways, right?

Sorry for posting potentially in the wrong thread.
Id be glad for help.
Fiona

Am So., 26. Mai 2019 um 16:11 Uhr schrieb Gosia Nowicka <
notifications@github.com>:

**Comment by gosianow** [comment]
Hi Fiona, 

it is fine that you post here your issues regarding DRIMSeq. I try to give you answer as soon as I can, but maybe if you care about faster feedback and better explanation about DEXSeq from the DEXSeq developers, maybe it is better if you post on Bioconductor support https://support.bioconductor.org/

So maybe if you do not get satisfying answer from me, please, post your question again on Bioconductor support. 

I think you have to have a better look on what is estimated with each model.
As I understand, the model that is used in DEXSeq is similar to Poisson regression 
log(E(Y|X)) ~ a + BX, 
but they use log2 instead of log (I assume, you could ask them to be sure). So B describes changes in log2(counts from a given transcript). 

The model in DRIMSeq is similar to logistic regression
log(p/(1-p)) ~ a + BX, there p is the probability of success (counts from a given transcript / counts from gene)

I think, the Bs from both models should correlate well, but they will not be identical, no matter if you take log, ln or log2. There is no way to derive log2(counts from a given transcript) from the model formula in DRIMSeq.


About the p-value distribution from DRIMSeq, the non uniform distribution suggests that this model is not the very "ideal" one, but often there is no "ideal" model available. I could think that probably genes with high number of transcripts are the one where the precision is challenging to estimate and they "cause" the distribution to pick around 1. I imagine what could help is to use more stringent filtering for the number of transcripts per gene, but you would have to find a cutoff where you still are able to keep transcripts of interest...

About the transcript coefficients being zero from your first post, you could also try `add_uniform = TRUE`, this option allows for the fitting of gene wise precision and coefficients for genes with two features having all zero for one group, or the last feature having all zero for one group.
 
Let me know if that helps,

Gosia

**Comment by fifdick** [comment]
This actually helps me immensely. Tha k you so much. I will try out all
suggestions and see how it goes.

Gosia Nowicka <notifications@github.com> schrieb am Mi., 12. Juni 2019,
10:53:
